[tool.poetry]
name = "gsa-scripts"
version = "0.1.0"
authors = ["Zxilly <zxilly@outlook.com>"]
license = "AGPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
tqdm = "^4.66.5"
matplotlib = "3.9.0"
psutil = "^6.0.0"
markdown-strings = "^3.4.0"
scour = "^0.38.2"

[tool.poetry.group.research]
optional = true

[tool.poetry.group.research.dependencies]
watchdog = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
